version: "3"
services:
  my-mongo:
    build: ./database
    image: "brunosimione/mydatabase"
    ports:
      - "27017:27017"
  my-api:
    build: ./api
    depends_on:
      - my-mongo
    image: "brunosimione/node_monolithic_api"
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    depends_on:
      - my-mongo
      - my-api
    links:
      - my-api
    image: "brunosimione/frontend"
    ports:
      - "3000:3000"